### ISSUE TITLE
redis is restarting 

### ISSUE THREAD

**Issue by chq3272991** [octohelm/harbor#431]
hi, I use the harbor （version v2.7.0  arm64）， and  use command (docker-compose ps) to watch container。
but , the container redis and harbor-jobservice is Restarting

there are some logs ：
redis:

```
[root@dc3-80-254 harbor]# docker logs 7ccda9a34831
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

harbor-jobservice:
```
2023-07-13T09:19:46Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:Get "http://core:8080/api/v2.0/internalconfig": dial tcp 172.23.0.3:8080: connect: connection refused, url:http://core:8080/api/v2.0/internalconfig
panic: failed to load configuration, error: failed to load rest config

goroutine 1 [running]:
main.main()
	/harbor/src/jobservice/main.go:42 +0x478
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2023-07-13T09:20:47Z [ERROR] [/pkg/registry/client.go:82]: Failed to parse REGISTRY_HTTP_CLIENT_TIMEOUT: strconv.ParseInt: parsing "": invalid syntax, use default value: 30m0s
2023-07-13T09:20:47Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2023-07-13T09:20:47Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.wasm.config.v1+json registered
```
can you give me some helps , thanks

**Comment by morlay** [comment]
@chq3272991 Don't use CentOS, or use external redis instead.
